apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80  # Service port
    targetPort: 8080
    protocol: TCP
  selector:
    app: fraud-detection-system  