apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-app-sa
  namespace: fraud-detection
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<aws_account_id>:role/eks-fraud-app-role
    

