spring:
  application:
    name: fraud-detection-system

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      cloudwatch:
        namespace: FraudDetection
        enabled: true
        step: 60

aws:
  region: ${AWS_REGION:<aws_region>}
  sqs:
    transaction-queue-url: ${TRANSACTION_QUEUE_URL}
    fraud-alert-queue-url: ${FRAUD_ALERT_QUEUE_URL}
  ecr:
    repository-url: ${ECR_REPOSITORY_URL}

logging:
  level:
    root: INFO
    com.frauddetection: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 